name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      # - name: Install Chrome
      #   run: |
      #      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #      sudo dpkg -i google-chrome-stable_current_amd64.deb

      - name: Run tests
        run: |
          apt-get install xvfb x11-apps x11-xkb-utils libx11-6 libx11-xcb1
          Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99
          npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Angular app
        run: ng build --configuration production --base-href="/angular-sandbox/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist/angular-sandbox
